### ISSUE TITLE
Fails to build with rust 1.30.0

### ISSUE THREAD

**Issue by asomers** [DavidDeSimone/mockitol#18]
Mock_derive fails to build with nightly 1.30.0.  I haven't tried with nightly 1.29.0, but I suspect it will fail too.
```
cargo +nightly-2018-09-06-x86_64-unknown-freebsd test
   Compiling unicode-xid v0.0.4
   Compiling quote v0.3.15
   Compiling lazy_static v0.2.11
   Compiling synom v0.11.3
   Compiling syn v0.11.11
   Compiling mock_derive v0.7.0 (file:///usr/home/somers/src/rust/mock_derive/mock_derive)
warning: the feature `proc_macro` has been stable since 1.29.0 and no longer requires an attribute to enable
  --> src/lib.rs:25:12
   |
25 | #![feature(proc_macro)]
   |            ^^^^^^^^^^
   |
   = note: #[warn(stable_features)] on by default

warning: the feature `proc_macro` has been stable since 1.29.0 and no longer requires an attribute to enable
  --> src/lib.rs:25:12
   |
25 | #![feature(proc_macro)]
   |            ^^^^^^^^^^
   |
   = note: #[warn(stable_features)] on by default

error[E0658]: procedural macros cannot expand to macro definitions (see issue #38356)
 --> examples/generics.rs:6:1
  |
6 | #[mock]
  | ^^^^^^^
  |
  = help: add #![feature(proc_macro_gen)] to the crate attributes to enable

error[E0658]: procedural macros cannot expand to macro definitions (see issue #38356)
 --> examples/simple.rs:6:1
  |
6 | #[mock]
  | ^^^^^^^
  |
  = help: add #![feature(proc_macro_gen)] to the crate attributes to enable

error[E0658]: procedural macros cannot expand to macro definitions (see issue #38356)
 --> examples/extern_functions.rs:9:1
  |
9 | #[mock]
  | ^^^^^^^
  |
  = help: add #![feature(proc_macro_gen)] to the crate attributes to enable

error[E0658]: procedural macros cannot expand to macro definitions (see issue #38356)
  --> examples/generics.rs:12:1
   |
12 | #[mock]
   | ^^^^^^^
   |
   = help: add #![feature(proc_macro_gen)] to the crate attributes to enable

error: aborting due to previous error
error: aborting due to 2 previous errors


For more information about this error, try `rustc --explain E0658`.
For more information about this error, try `rustc --explain E0658`.
error: Could not compile `mock_derive`.
warning: build failed, waiting for other jobs to finish...
error: Could not compile `mock_derive`.
warning: build failed, waiting for other jobs to finish...
error[E0658]: procedural macros cannot expand to macro definitions (see issue #38356)
  --> examples/extern_functions.rs:17:1
   |
17 | #[mock]
   | ^^^^^^^
   |
   = help: add #![feature(proc_macro_gen)] to the crate attributes to enable

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `mock_derive`.

To learn more, run the command again with --verbose.
```

**Comment by DavidDeSimone** [comment]
Thank you for making this issue. I know this was years ago, however I had life circumstances that prevented me from contributing. I have now fixed this issue on master.
